apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "discord-tech-news-notifier.volumeClaimName" . }}
spec:
  capacity:
    storage: {{ .Values.volume.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volume.hostPath }}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "discord-tech-news-notifier.volumeClaimName" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.capacity }}
  volumeName: {{ include "discord-tech-news-notifier.volumeClaimName" . }}
