name: 'Build image'
on:
  push:
    branches:
      - 'main'

  schedule:
    - cron: '0 1 * * 1'

permissions:
  contents: write
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compute tag
        id: vars
        run: |
          TAG=$(git tag | sort --version-sort | tail -n1)
          TMP=${TAG%.*}
          MINOR=${TMP#*.}
          NEW_TAG=${TAG%%.*}.$((MINOR + 1)).0
          echo "tag=$(echo "${NEW_TAG:1}")" >> $GITHUB_OUTPUT
          echo "current_tag=$(echo "${TAG:1}")" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (amd)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            azalax/discordtechnewsnotifier:latest
            azalax/discordtechnewsnotifier:${{ steps.vars.outputs.tag }}
            ghcr.io/ludovicalarcon/discordtechnewsnotifier:latest
            ghcr.io/ludovicalarcon/discordtechnewsnotifier:${{ steps.vars.outputs.tag }}

      - name: Build and push (arm)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile_arm
          push: true
          tags: |
            azalax/discordtechnewsnotifier:${{ steps.vars.outputs.tag }}_arm
            ghcr.io/ludovicalarcon/discordtechnewsnotifier:${{ steps.vars.outputs.tag }}_arm

      - name: Update Chart Version
        run: |
          sed -i 's/${{ steps.vars.outputs.current_tag }}/${{ steps.vars.outputs.tag }}/' charts/Chart.yaml
          sed -i 's/${{ steps.vars.outputs.current_tag }}/${{ steps.vars.outputs.tag }}/' charts/values.yaml

          git config --global user.name "ci-bot"
          git config --global user.email "ci-bot@ludovicalarcon.noreply.github.com"
          git add .
          git commit -m "Update version"
          git push

      - name: Update Tag
        run: |
          git tag -a v${{ steps.vars.outputs.tag }} -m "v${{ steps.vars.outputs.tag }}"
          git push origin v${{ steps.vars.outputs.tag }}
