name: Helm
on: [push]

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download helm
        run: |
          curl -O https://get.helm.sh/helm-v3.10.3-linux-amd64.tar.gz
          tar -zxvf helm-v3.10.3-linux-amd64.tar.gz
          mv linux-amd64/helm .
          ./helm version
          ls -la

      - name: Helm template
        run: ./helm template charts/ --debug --set="discordWebhook.url"="foo"

      - name: Helm unittest
        run: |
          ./helm plugin install https://github.com/quintush/helm-unittest
          ./helm unittest charts/ -3
